In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.5'

In [3]:
# matriz 2D
m = np.matrix("1,2,3; 4,5,6")
print(m)

[[1 2 3]
 [4 5 6]]


In [4]:
m = np.matrix([[1,3],[2,4]])
print(m)

[[1 3]
 [2 4]]


In [5]:
m[1,1]

4

In [6]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a * a # elemento por elemento (elementos correspondentes)

array([[ 1,  4],
       [ 9, 16]])

In [8]:
a-a

array([[0, 0],
       [0, 0]])

In [9]:
# cast ndarray -> matrix
m = np.mat(a)
m

matrix([[1, 2],
        [3, 4]])

In [10]:
# 1 linha com N  por 1 coluna com N
# dot product
m*m 

matrix([[ 7, 10],
        [15, 22]])

In [11]:
# dot product em arrays
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [12]:
# cast array -> matrix
a = np.array([[1,2],[3,4]])

m = np.asmatrix(a)
m

matrix([[1, 2],
        [3, 4]])

In [13]:
# cast matrix -> array
a = np.asarray(m)
a


array([[1, 2],
       [3, 4]])

In [24]:
a = np.ones((2,3))

In [29]:
a.shape[0] # quantidade de linhas

2

In [30]:
a.shape[1] # quantidade de colunas

3

In [31]:
a.shape

(2, 3)