In [2]:
import numpy as np
import sys
print(sys.version)
np.__version__

3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0]


'1.18.5'

In [11]:
a = np.arange(13)

In [4]:
a.std()

3.452052529534663

In [10]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [16]:
a1 = np.ones([4])
a2 = np.arange(15)

In [18]:
#concatenacao
a = np.concatenate((a1, a2))
a

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

In [21]:
a1 = np.ones((3,3))
a2 = np.zeros((3,3))

In [23]:
# join 
a = np.vstack((a1, a2))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# join 
a = np.hstack((a1, a2))
a

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [28]:
a = np.array([0,1,2])
b = np.array([3,4,5])
c = np.array([6,7,8])
print (a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [26]:
#join
m = np.column_stack((a,b,c))
m

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [27]:
#join
m = np.row_stack((a,b,c))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
# split
a = np.arange(16)

In [30]:
# reshape -> unidimensional para bidimensional
a1 = a.reshape((4,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
# divisao de array
[a_p1, a_p2] = np.hsplit(a1, 2)

In [33]:
a_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [35]:
a_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [37]:
# divisao de array
[a_p1, a_p2] = np.vsplit(a1, 2)

In [38]:
a_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [39]:
a_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
np.vsplit(a1, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [45]:
# write / save
filename = 'datasets/dados_saved.npy'
dados = a1
np.save(filename, dados)

In [46]:
# load / read
dados2 = np.load(filename)
dados2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])