In [1]:
import numpy as np
np.__version__

'1.18.5'

In [3]:
a = np.random.randint(0,50,20)
a

array([ 9, 20, 29, 39,  8, 42, 46,  5, 26, 23, 44, 40, 38, 23, 33, 10, 17,
       24, 15, 49])

In [6]:
def calc_func(x):
    if x < 10:
        return x**3
    else:
        return x**2
    

In [13]:
# funcao vetorizada para aplicar a cada elemento de array
v_calc_func = np.vectorize(calc_func)

In [14]:
v_calc_func(a)

array([ 729,  400,  841, 1521,  512, 1764, 2116,  125,  676,  529, 1936,
       1600, 1444,  529, 1089,  100,  289,  576,  225, 2401])

In [16]:
list(map(calc_func, a))

[729,
 400,
 841,
 1521,
 512,
 1764,
 2116,
 125,
 676,
 529,
 1936,
 1600,
 1444,
 529,
 1089,
 100,
 289,
 576,
 225,
 2401]

In [17]:
[calc_func(x) for x in a]

[729,
 400,
 841,
 1521,
 512,
 1764,
 2116,
 125,
 676,
 529,
 1936,
 1600,
 1444,
 529,
 1089,
 100,
 289,
 576,
 225,
 2401]

In [21]:
%timeit [calc_func(x) for x in a]
%timeit v_calc_func(a)
%timeit list(map(calc_func, a))

9.95 µs ± 120 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
16.4 µs ± 342 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9.59 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [30]:
a = np.random.randint(0,100,20*10000)
# np.random.randint(start, end, repeats)

a


array([22, 73, 37, ..., 15, 69, 62])

In [31]:
%timeit [calc_func(x) for x in a]
%timeit v_calc_func(a)
%timeit list(map(calc_func, a))

112 ms ± 8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
62.2 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
111 ms ± 3.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
